### ISSUE TITLE
Additional Stat

### ISSUE THREAD

**Issue by bs-in-co** [tak-ps/stats#1]
Would like to add an additional table for "business category". Would also be interested in having data presented as both a table and a pie chart eventually, perhaps with an option to toggle between the two?

**Comment by ingalls** [comment]
![Screenshot from 2022-11-28 16-00-02](https://user-images.githubusercontent.com/1297009/204398755-3a1ffd7c-cd24-46a4-bbd7-f6681e945572.png)

Business Category should already be recorded per above. Will get on the Pie Chart.

**Comment by ingalls** [comment]
![Screenshot from 2022-11-28 16-31-42](https://user-images.githubusercontent.com/1297009/204402599-b5b68d1b-d39d-40ea-a0a2-79223bec5b7d.png)
